apiVersion: apps/v1
kind: Deployment
metadata:
  name: personalweb-deployment
  labels:
    app: personalweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personalweb
      service: http-server
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: personalweb
        service: http-server
  
  spec:
    containers:
    - name: personalweb
      image: robertsuhim/personalweb:latest
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80